Fix oops on 2.6.25 guest (Rusty Russell)
Eduardo Habkost wrote:
> On Mon, May 04, 2009 at 07:47:07PM -0400, john cooper wrote:
>
>>>>>> commit 90b5ac3c75f747d5529586bd07fe75ce926ccb75
>>>>>> Author: aliguori <aliguori>
>>>>>> Date:   Sun Apr 5 17:40:08 2009 +0000
>>>>>>
>>>>>>     Fix oops on 2.6.25 guest (Rusty Russell)
>>>>>>         I believe this is behind the following:
>>>>>>
>>>>>> https://bugs.edge.launchpad.net/ubuntu/jaunty/+source/linux/+bug/331128
>>>>>>
>>>>>>         virtio_pci in 2.6.25 didn't do feature negotiation
>>>>>> correctly: it acked every
>>>>>>     bit.  Fortunately, we can detect this.
>>>>>>
>>>>>>
>>>>> Conflict on cherry-pick. Needs backport.
>>>>>
>> Backport attached.
>>
>
> Removed from the queue, due to:
>
> gcc -I. -I.. -I/home/ehabkost/code/kvm/kvm-userspace/qemu/target-i386 -I/home/ehabkost/code/kvm/kvm-userspace/qemu -MMD -MT virtio.o -MP -DNEED_CPU_H -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__user= -I/home/ehabkost/code/kvm/kvm-userspace/qemu/tcg -I/home/ehabkost/code/kvm/kvm-userspace/qemu/tcg/x86_64 -I/home/ehabkost/code/kvm/kvm-userspace/qemu/fpu   -DHAS_AUDIO -DHAS_AUDIO_CHOICE -I/home/ehabkost/code/kvm/kvm-userspace/qemu/slirp -I /home/ehabkost/code/kvm/kvm-userspace/qemu/../libkvm  -DCONFIG_X86 -O2 -g -fno-strict-aliasing -Wall -Wundef -Wendif-labels -Wwrite-strings -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls  -m64 -I /mnt/common/code/kvm/kvm-userspace/kernel/include -c -o virtio.o /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c: In function ‘virtio_ioport_write’:
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c:521: error: ‘VIRTIO_F_BAD_FEATURE’ undeclared (first use in this function)
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c:521: error: (Each undeclared identifier is reported only once
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c:521: error: for each function it appears in.)
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c: In function ‘virtio_ioport_read’:
> /home/ehabkost/code/kvm/kvm-userspace/qemu/hw/virtio.c:566: error: ‘VIRTIO_F_BAD_FEATURE’ undeclared (first use in this function)
> make[2]: *** [virtio.o] Error 1
> make[2]: Leaving directory `/mnt/common/code/kvm/kvm-userspace/qemu/x86_64-softmmu'
> make[1]: *** [subdir-x86_64-softmmu] Error 2
> make[1]: Leaving directory `/mnt/common/code/kvm/kvm-userspace/qemu'
> make: *** [qemu] Error 2
>
Was missing from the upstream patch, I've included
it here.  I built the tree and did a trivial test
boot.  Update attached.

-john

--
john.cooper@redhat.com

commit 90b5ac3c75f747d5529586bd07fe75ce926ccb75
Author: aliguori <aliguori>
Date:   Sun Apr 5 17:40:08 2009 +0000

    Fix oops on 2.6.25 guest (Rusty Russell)

    I believe this is behind the following:
    https://bugs.edge.launchpad.net/ubuntu/jaunty/+source/linux/+bug/331128

    virtio_pci in 2.6.25 didn't do feature negotiation correctly: it acked every
    bit.  Fortunately, we can detect this.

    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
    Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

    Backport to rhev kvm-userspace <john.cooper@redhat.com>

Message-ID: <4A01B6BD.70506@redhat.com>
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>
RH-Upstream-status: applied(qemu/master)
Bugzilla: 501729
Message-ID: <20090511162717.GG4871@blackpad>
Acked-by: Zachary Amsden <zamsden@redhat.com>
Acked-by: "Michael S. Tsirkin" <mst@redhat.com>
Acked-by: john cooper <john.cooper@redhat.com>