kvm: qemu: re-add missing declarations for qemu_{shutdown, powerdown, reset}_requested
The following patch re applies the declarations added to qemu/vl.h in
469b506a270347a88d11c65392ac1df7b476d176 and which were missed in merge
f4b21ce8084fc3ffcfc1a2b92bd26466700d3d40, resulting in the following
compilation warnings :

  qemu/qemu-kvm.c:343: warning: implicit declaration of function `qemu_shutdown_requested'
  qemu/qemu-kvm.c:345: warning: implicit declaration of function `qemu_powerdown_requested'
  qemu/qemu-kvm.c:347: warning: implicit declaration of function `qemu_reset_requested'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>