kvm: qemu: re-add declaration of qemu_get_launch_info()
somehow missing from sysemu.h after a qemu merge and otherwise complaining
with the following warning :

  kvm-71/qemu/migration.c: In function 'migration_init_ssh':
  kvm-71/qemu/migration.c:629: warning: implicit declaration of function 'qemu_get_launch_info'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>