kvm: qemu: add missing declarations for monitor_{resume, suspend}
The following patch fixes :

  qemu/migration.c:210: warning: implicit declaration of function `monitor_resume'
  qemu/migration.c:507: warning: implicit declaration of function `monitor_suspend'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>