kvm: libkvm: export init for coalesced MMIO support
complement 2680f3df932a3119880a692609943587ecc8f409 to export the
definition for kvm_init_coalesced_mmio as it is used by the per
arch libkvm as shown by the following warning :

  libkvm-x86.c: In function 'kvm_arch_create':
  libkvm-x86.c:182: warning: implicit declaration of function 'kvm_init_coalesced_mmio'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>