kvm: qemu: device-assignment: don't use libkvm's private get_slot()
get_slot() isn't exported by libkvm, so we shouldn't be using it.

The worst thing that can happen because of this change is that
libkvm will spew a warning. It looks to me like that can't happen
though.

Fixes:

  qemu/hw/device-assignment.c:161: warning: implicit declaration of function ‘get_slot’

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Avi Kivity <avi@redhat.com>
(cherry picked from commit f2bc1b43758452d89709473bf40bd4cfe628574e)
Signed-off-by: Chris Wright <chrisw@redhat.com>
Bugzilla: 498084
Message-Id: <1242950924-30161-2-git-send-email-chrisw@redhat.com>
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>
RH-Upstream-status: applied
Acked-by: Juan Quintela <quintela@redhat.com>
Acked-by: Marcelo Tosatti <mtosatti@redhat.com>
Acked-by: Don Dutile <ddutile@redhat.com>