kvm: qemu: re-add missing declarations for qemu_live_{savevm, loadvm}_state
The following patch re applies the declarations added to qemu/vl.h in
4213cbcf86847c8568d0147bd055d6a13bb1c963 and which were missed in merge
f4b21ce8084fc3ffcfc1a2b92bd26466700d3d40, resulting in the following
compilation warnings :

  qemu/migration.c:193: warning: implicit declaration of function `qemu_live_savevm_state'
  qemu/migration.c:855: warning: implicit declaration of function `qemu_live_loadvm_state'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>