kvm: qemu: fix compilation w/out KVM_CAP_MP_STATE
Add kvm_reset_mpstate inline function and only call it when
KVM_CAP_MP_STATE is defined.

qemu/qemu-kvm-x86.c:677: error: unknown field `mp_state' specified in initializer
qemu/qemu-kvm-x86.c:677: error: `KVM_MP_STATE_UNINITIALIZED' undeclared (first use in this function)
...

Signed-off-by: Chris Wright <chrisw@sous-sol.org>
Signed-off-by: Avi Kivity <avi@qumranet.com>