kvm: qemu: add missing declaration for bdrv_flush_all
The following patch fixes :

  qemu/migration.c:187: warning: implicit declaration of function `bdrv_flush_all'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>